# Generated by Django 5.1.7 on 2025-03-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image_url', models.URLField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.destination')),
            ],
        ),
    ]
